/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AuthSingInRouteImport } from './pages/_auth/sing-in'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSingInRoute = AuthSingInRouteImport.update({
  id: '/_auth/sing-in',
  path: '/sing-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/sing-in': typeof AuthSingInRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/sing-in': typeof AuthSingInRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth/sing-in': typeof AuthSingInRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sing-in' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/sing-in' | '/'
  id: '__root__' | '/_auth/sing-in' | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthSingInRoute: typeof AuthSingInRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sing-in': {
      id: '/_auth/sing-in'
      path: '/sing-in'
      fullPath: '/sing-in'
      preLoaderRoute: typeof AuthSingInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthSingInRoute: AuthSingInRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
