/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AuthIndexRouteImport } from './pages/auth/index'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AppProfileIndexRouteImport } from './pages/_app/profile/index'
import { Route as AppPokemonsIndexRouteImport } from './pages/_app/pokemons/index'
import { Route as AppInsightsIndexRouteImport } from './pages/_app/insights/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppPokemonsIndexRoute = AppPokemonsIndexRouteImport.update({
  id: '/pokemons/',
  path: '/pokemons/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppInsightsIndexRoute = AppInsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/insights': typeof AppInsightsIndexRoute
  '/pokemons': typeof AppPokemonsIndexRoute
  '/profile': typeof AppProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/insights': typeof AppInsightsIndexRoute
  '/pokemons': typeof AppPokemonsIndexRoute
  '/profile': typeof AppProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_app/insights/': typeof AppInsightsIndexRoute
  '/_app/pokemons/': typeof AppPokemonsIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/insights' | '/pokemons' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/insights' | '/pokemons' | '/profile'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/auth/'
    | '/_app/insights/'
    | '/_app/pokemons/'
    | '/_app/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/pokemons/': {
      id: '/_app/pokemons/'
      path: '/pokemons'
      fullPath: '/pokemons'
      preLoaderRoute: typeof AppPokemonsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/insights/': {
      id: '/_app/insights/'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppInsightsIndexRoute: typeof AppInsightsIndexRoute
  AppPokemonsIndexRoute: typeof AppPokemonsIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppInsightsIndexRoute: AppInsightsIndexRoute,
  AppPokemonsIndexRoute: AppPokemonsIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
